<?php

namespace Org\CoreBundle\Propel\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'custom_lists' table.
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * 10/10/15 12:14:54
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.src.Org.CoreBundle.Propel.map
 */
class CustomListsTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'src.Org.CoreBundle.Propel.map.CustomListsTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('custom_lists');
        $this->setPhpName('CustomLists');
        $this->setClassname('Org\\CoreBundle\\Propel\\CustomLists');
        $this->setPackage('src.Org.CoreBundle.Propel');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('id_custom_list', 'IdCustomList', 'INTEGER', true, null, null);
        $this->addColumn('list_name', 'ListName', 'VARCHAR', false, 45, null);
        $this->addForeignKey('id_user', 'IdUser', 'INTEGER', 'fos_user', 'id', true, null, null);
        $this->addColumn('created_at', 'CreatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('updated_at', 'UpdatedAt', 'TIMESTAMP', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('User', 'FOS\\UserBundle\\Propel\\User', RelationMap::MANY_TO_ONE, array('id_user' => 'id', ), 'CASCADE', 'CASCADE');
        $this->addRelation('CustomListElement', 'Org\\CoreBundle\\Propel\\CustomListElement', RelationMap::ONE_TO_MANY, array('id_custom_list' => 'custom_list', ), 'CASCADE', 'CASCADE', 'CustomListElements');
        $this->addRelation('CyclicalEventHasList', 'Org\\CoreBundle\\Propel\\CyclicalEventHasList', RelationMap::ONE_TO_MANY, array('id_custom_list' => 'id_list', ), 'CASCADE', 'CASCADE', 'CyclicalEventHasLists');
        $this->addRelation('EventHasList', 'Org\\CoreBundle\\Propel\\EventHasList', RelationMap::ONE_TO_MANY, array('id_custom_list' => 'id_list', ), 'CASCADE', 'CASCADE', 'EventHasLists');
        $this->addRelation('CyclicalEvents', 'Org\\CoreBundle\\Propel\\CyclicalEvents', RelationMap::MANY_TO_MANY, array(), 'CASCADE', 'CASCADE', 'CyclicalEventss');
        $this->addRelation('Events', 'Org\\CoreBundle\\Propel\\Events', RelationMap::MANY_TO_MANY, array(), 'CASCADE', 'CASCADE', 'Eventss');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'timestampable' =>  array (
  'create_column' => 'created_at',
  'update_column' => 'updated_at',
  'disable_updated_at' => 'false',
),
        );
    } // getBehaviors()

} // CustomListsTableMap
