<?php

namespace Org\CoreBundle\Propel\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'cyclical_event_has_list' table.
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * 10/10/15 12:14:55
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.src.Org.CoreBundle.Propel.map
 */
class CyclicalEventHasListTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'src.Org.CoreBundle.Propel.map.CyclicalEventHasListTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('cyclical_event_has_list');
        $this->setPhpName('CyclicalEventHasList');
        $this->setClassname('Org\\CoreBundle\\Propel\\CyclicalEventHasList');
        $this->setPackage('src.Org.CoreBundle.Propel');
        $this->setUseIdGenerator(false);
        $this->setIsCrossRef(true);
        // columns
        $this->addForeignPrimaryKey('id_cyclical_event', 'IdCyclicalEvent', 'INTEGER' , 'cyclical_events', 'id_cyclical_event', true, null, null);
        $this->addForeignPrimaryKey('id_list', 'IdList', 'INTEGER' , 'custom_lists', 'id_custom_list', true, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('CyclicalEvents', 'Org\\CoreBundle\\Propel\\CyclicalEvents', RelationMap::MANY_TO_ONE, array('id_cyclical_event' => 'id_cyclical_event', ), 'CASCADE', 'CASCADE');
        $this->addRelation('CustomLists', 'Org\\CoreBundle\\Propel\\CustomLists', RelationMap::MANY_TO_ONE, array('id_list' => 'id_custom_list', ), 'CASCADE', 'CASCADE');
    } // buildRelations()

} // CyclicalEventHasListTableMap
